/**
 * Fixed, curated list of standard Discogs format names (spec FR-009,
 * feature 038 — regenerated from the 51-value formats-distinct.json
 * catalog, replacing the prior 33-value list from feature 022).
 * No Discogs endpoint enumerates valid format values, so this list is
 * maintained statically. Declaration order is the canonical order used
 * everywhere a format selection is serialized or rendered (URL params,
 * checkbox list, active-filter display).
 */

export const FORMAT_OPTIONS: readonly string[] = [
  '4-Track Cartridge',
  '8-Track Cartridge',
  'Acetate',
  'All Media',
  'Betacam',
  'Betacam SP',
  'Betamax',
  'Blu-ray',
  'Blu-ray-R',
  'Box Set',
  'CD',
  'CDV',
  'CDr',
  'Cassette',
  'Cylinder',
  'DAT',
  'DCC',
  'DVD',
  'DVDr',
  'DualDisc',
  'Edison Disc',
  'Elcaset',
  'File',
  'Flexi-disc',
  'Floppy Disk',
  'HD DVD',
  'HD DVD-R',
  'Hybrid',
  'Laserdisc',
  'Lathe Cut',
  'MVD',
  'Memory Stick',
  'Microcassette',
  'MiniDV',
  'Minidisc',
  'Pathé Disc',
  'PlayTape',
  'RCA Tape Cartridge',
  'Reel-To-Reel',
  'SACD',
  'SelectaVision',
  'Shellac',
  'Tefifon',
  'U-matic',
  'UMD',
  'VHD',
  'VHS',
  'Video 2000',
  'Video8',
  'Vinyl',
  'Wire Recording',
];
